rubric:
  possibleScore:
  - requirement: correct implementation of required functionality
    points: 50
  - requirement: code quality (how easy is your solution to follow)
    points: 10
  possibleExtraCredotScore:
  - requirement: implement < and > redirection
    points: 10
  - requirement: implement append >> redirection
    points: 5
  requirements:
  - description: implement the cd internal command
    criteria:
    - cd command is implemented directly in code
    - with no arguments does nothing
    - with 1 argument changes directory of the current process to the argument
  - description: implement the exit internal command
    criteria:
    - exit command is implemented directly in code
    - exits the process with return code 0
  - description: implement other commands with fork/exec and pipe support
    criteria:
    - other than exit and cd, other commands should be implemented with fork/exec
    - multiple commands with pipes must be supported
  - description: optional extra credit to implement < and > file redirction
    criteria:
    - must support file redirection with < and >
  - description: optional extra credit to implement append >> redirection
    criteria:
    - must support append redirection with >>
    
